
CPPFLAGS = --std=c++17 -Wall -I. -O3 -Wno-format

all:
	g++ $(CPPFLAGS) listing_0066_haversine_generator_main.cpp -o listing_0066_haversine_generator_main
	g++ $(CPPFLAGS) listing_0067_simple_haversine_main.cpp -o listing_0067_simple_haversine_main
	g++ $(CPPFLAGS) listing_0071_os_timer_main.cpp -o listing_0071_os_timer_main
	g++ $(CPPFLAGS) listing_0072_cpu_timer_main.cpp -o listing_0072_cpu_timer_main
	g++ $(CPPFLAGS) listing_0073_cpu_timer_guessfreq_main.cpp -o listing_0073_cpu_timer_guessfreq_main
	g++ $(CPPFLAGS) listing_0078_profiled_haversine_main.cpp -o listing_0078_profiled_haversine_main
	g++ $(CPPFLAGS) listing_0080_double_counted_haversine_main.cpp -o listing_0080_double_counted_haversine_main

clean:
	rm -f listing_0066_haversine_generator_main
	rm -f listing_0067_simple_haversine_main
	rm -f listing_0071_os_timer_main
	rm -f listing_0072_cpu_timer_main
	rm -f listing_0073_cpu_timer_guessfreq_main
	rm -f listing_0078_profiled_haversine_main
	rm -f listing_0080_double_counted_haversine_main
