
CPPFLAGS = --std=c++17 -Wall -I. -O3 -Wno-format
#CPPFLAGS = --std=c++17 -Wall -I. -g -Wno-format

all:
	#g++ $(CPPFLAGS) listing_0066_haversine_generator_main.cpp -o listing_0066_haversine_generator_main
	#g++ $(CPPFLAGS) listing_0067_simple_haversine_main.cpp -o listing_0067_simple_haversine_main
	#g++ $(CPPFLAGS) listing_0071_os_timer_main.cpp -o listing_0071_os_timer_main
	#g++ $(CPPFLAGS) listing_0072_cpu_timer_main.cpp -o listing_0072_cpu_timer_main
	#g++ $(CPPFLAGS) listing_0073_cpu_timer_guessfreq_main.cpp -o listing_0073_cpu_timer_guessfreq_main
	#g++ $(CPPFLAGS) listing_0078_profiled_haversine_main.cpp -o listing_0078_profiled_haversine_main
	#g++ $(CPPFLAGS) listing_0080_double_counted_haversine_main.cpp -o listing_0080_double_counted_haversine_main
	#g++ $(CPPFLAGS) listing_0084_recursive_timed_haversine_main.cpp -o listing_0084_recursive_timed_haversine_main
	#g++ $(CPPFLAGS) listing_0084_recursive_timed_haversine_main.cpp -o listing_0084_recursive_timed_haversine_main
	#g++ $(CPPFLAGS) listing_0092_profiler_on_haversine_main.cpp -o listing_0092_profiler_on_haversine_main
	#g++ $(CPPFLAGS) listing_0093_profiler_off_haversine_main.cpp -o listing_0093_profiler_off_haversine_main
	#g++ $(CPPFLAGS) listing_0095_profiled_haversine_main.cpp -o listing_0095_profiled_haversine_main
	#g++ $(CPPFLAGS) listing_0097_tsc_select_main.cpp -o listing_0097_tsc_select_main
	#g++ $(CPPFLAGS) listing_0098_qpc_select_main.cpp -o listing_0098_qpc_select_main
	#g++ $(CPPFLAGS) listing_0099_qpc_minimal_blocks_main.cpp -o listing_0099_qpc_minimal_blocks_main
	#g++ $(CPPFLAGS) listing_0104_read_overhead_main.cpp -o listing_0104_read_overhead_main
	#g++ $(CPPFLAGS) listing_0107_mallocread_overhead_main.cpp -o listing_0107_mallocread_overhead_main
	g++ $(CPPFLAGS) listing_0111_pagefault_overhead_main.cpp -o listing_0111_pagefault_overhead_main

clean:
	#rm -f listing_0066_haversine_generator_main
	#rm -f listing_0067_simple_haversine_main
	#rm -f listing_0071_os_timer_main
	#rm -f listing_0072_cpu_timer_main
	#rm -f listing_0073_cpu_timer_guessfreq_main
	#rm -f listing_0078_profiled_haversine_main
	#rm -f listing_0080_double_counted_haversine_main
	#rm -f listing_0084_recursive_timed_haversine_main
	#rm -f listing_0092_profiler_on_haversine_main
	#rm -f listing_0093_profiler_off_haversine_main
	#rm -f listing_0095_profiled_haversine_main
	#rm -f listing_0097_tsc_select_main
	#rm -f listing_0098_qpc_select_main
	#rm -f listing_0099_qpc_minimal_blocks_main
	#rm -f listing_0104_read_overhead_main
	#rm -f listing_0107_mallocread_overhead_main
	rm -f listing_0111_pagefault_overhead_main
